### ISSUE TITLE
Clinic icon

### ISSUE THREAD

**Issue by kocio-pl** [nebulon42/osmic#22]
Are you interested in PR of the [clinic icon](https://github.com/kocio-pl/openstreetmap-carto/blob/master/symbols/clinic.16.svg) (simple cross derived from the hospital SVG icon)?

**Comment by nebulon42** [comment]
What do you mean by interested? Is this an icon request or do you want me to comment on the PR? (You can subscribe people by mentioning them e.g. @kocio-pl.)

**Comment by kocio-pl** [comment]
I mean puting it into Osmic icon set, so probably - if I can made a PR. Of course I can do it anyway =} , but don't know if it's worth trying, because playing with Git/GitHub still requires me to concentrate.

**Comment by nebulon42** [comment]
I see. I'm not sure about clinic and the symbol as it is very close to the existing hospital icon. Clinic represents something in the middle between doctors and hospital, right? Maybe re-using either doctors or hospital would be an option?

**Comment by dieterdreist** [comment]
> Am 13.04.2015 um 17:46 schrieb nebulon42 <notifications@github.com>:
> 
> Clinic represents something in the middle between doctors and hospital,



generally yes, I believe when they are run privately they will always call themselves clinic (at least around here), even if they are quite big and provide serious medical services superior to some hospitals

**Comment by kocio-pl** [comment]
Clinic is somewhat cryptic for me, looking at Wikipedia entry - it can be anything from doctors to hospital (or even part of the hospital). But the doctors also can be building with the enclosing area (I know some around me), while the hospital can also be just a small building (I also know such cases) and all the naming like doctors/clinic is somewhat messed up with no real guidance from OSM Wiki how to tell which of these 3 cases should be used.

We were discussing it here:

https://github.com/gravitystorm/openstreetmap-carto/issues/763

and the bottom line was the cross would be the best (although it was very small debate).

I think cross may be useful for other purposes, but I don't know what's your goal with Osmic - having every useful icon around or just those which have clear meaning in OSM?

**Comment by dieterdreist** [comment]
> Am 13.04.2015 um 18:07 schrieb kocio-pl <notifications@github.com>:
> 
> I think cross may be useful for other purposes, but I don't know what's your goal with Osmic - having every useful icon around or just those which have clear meaning in OSM?


isn't the cross a christian symbol?

**Comment by kocio-pl** [comment]
Symbols, especially simple geometric shapes like this, can have many interpretations. Of course it is also the Christian symbol, but it could have many forms then:

https://en.wikipedia.org/wiki/Christian_cross#Forms

This one is a Greek cross (used in current hospital, doctor's office and pharmacy icons), while on OSM we use Latin cross to indicate religious context.

I guess the problem with clear religious background (red cross/crescent/shield of David/whatever) was a driving force to introduce neutral Red Crystal in 2005:

https://en.wikipedia.org/wiki/Emblems_of_the_International_Red_Cross_and_Red_Crescent_Movement#Red_Crystal

I would be happy to use it on the map to avoid the confusion and regional differences, but it's too early to be recognized (I just read about it trying to answer you) and probably it's not that simple.

**Comment by nebulon42** [comment]
The cross might be an issue since it violates the Geneva convention. This is also problematic regarding pharmacy, doctors and hospital. Leaving this aside and not thinking of the ambiguity of the clinic definition the cross IMO is still too close to hospital to convey a distinct meaning.

So we would need something more distinct for clinic, but here again the ambiguity of the definition comes into play. I currently have no solution for this.

**Comment by kocio-pl** [comment]
I'm not sure, but probably it has to be red to be covered by Geneva convention and we use different color (purple or just white - with purple background - as in pharmacy).

**Comment by nebulon42** [comment]
Closing this as of https://github.com/gravitystorm/openstreetmap-carto/pull/1565.
