### ISSUE TITLE
Add icon for waterfall.

### ISSUE THREAD

**Issue by StyXman** [nebulon42/osmic#27]
I know this is not rendered by OSM by default, but it would be nice to have it available for other renderings. I have the impression that at least one well known alternative rendering of OSM data has them rendered.

**Comment by nebulon42** [comment]
Being rendered by osm-carto is not a requirement. :) If you have any examples I'm happy if you link them.

**Comment by StyXman** [comment]
Nothing with the proper license, and i don't know how 'inspiration' works in that case. I think that something like three 'eshes' (ʃʃʃ) with a squiggle at the bottom should be enough.

**Comment by nebulon42** [comment]
That's what I had in mind, too.
