### ISSUE TITLE
new icon for memorial

### ISSUE THREAD

**Issue by nebulon42** [nebulon42/osmic#29]
as the current one is more suited for grave yard.

Maybe use current monument icon for memorial and make another one for monument.

**Comment by dieterdreist** [comment]
> Am 22.05.2015 um 09:35 schrieb nebulon42 <notifications@github.com>:
> 
> Maybe use current monument icon for memorial and make another one for monument.


the monument icon is too monumental for memorials IMHO

**Comment by nebulon42** [comment]
May be the case, but I'm having no other ideas just yet, will think of it some more. Do you have an opinion on the "current memorial icon looks like grave yard" observation?

**Comment by matkoniecz** [comment]
> current memorial icon looks like grave yard

IMHO it is true.
