### ISSUE TITLE
Icon for fort 

### ISSUE THREAD

**Issue by StyXman** [nebulon42/osmic#30]
an icon for representing modern (16th c.+) forts. here's an image of one showing its caracteristics:

http://en.wikipedia.org/wiki/Fortification#/media/File:Fortbourtange.jpg

A basic attempt of my own:

![fort 24](https://cloud.githubusercontent.com/assets/167327/7800339/0df75b1a-0314-11e5-91fe-9e66e2925094.png)

**Comment by matkoniecz** [comment]
For me this icon looks like a flower.

**Comment by nebulon42** [comment]
IMO top views should be avoided. I will try to draft something in line with the icons of castles that are already in.

**Comment by StyXman** [comment]
The view of a fort from the side, at least the one I see regularly as it's in the border of my town and others in the region, is a rectangle with a slanted base, D-laying-on-its-back shaped windows for cannons in the vertical section of the wall, and maybe a building jutting up from the inside with a flag on top and some guard towers in the corners. This could easily be only Vauban's style (I'm not expert), but other I've seen elsewhere (Italy, mostly) are similar. Here are some photos of the local one:

http://petitcba.homenet.org/~mdione/PhotoShow/?f=lugares%2FEuropa%2FFrance%2FAntibes%2F2009-11-11T16%3A58%3A04.jpg

**Comment by nebulon42** [comment]
Did you have something like that in mind?
![fort-14](https://cloud.githubusercontent.com/assets/3531092/8271655/31635288-1823-11e5-8e86-f7e7bc104fd7.png)

**Comment by nebulon42** [comment]
Closing for now, feel free to discuss further.
