### ISSUE TITLE
icon for town hall

### ISSUE THREAD

**Issue by nebulon42** [nebulon42/osmic#5]
Request from https://github.com/gravitystorm/openstreetmap-carto/issues/77.
First idea: building with a flag on top
Be careful not to make it too similar with museum.

**Comment by althio** [comment]
> First idea: building with a flag on top

That is what I was going to suggest! ;)
Keep going please!

**Comment by nebulon42** [comment]
There is now a first version of town hall ([town-hall-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/town-hall-16.svg)) alongside with an icon for government facilities ([government-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/government-16.svg)).
