### ISSUE TITLE
Add icon for amenity=bicycle_parking

### ISSUE THREAD

**Issue by math1985** [nebulon42/osmic#6]
Thanks for your contributions!

Would it be possible (no hurry) to also create an icon for amenity=bicycle_parking?

**Comment by math1985** [comment]
Current icon in SJJB repository: http://www.sjjb.co.uk/mapicons/svg/transport/parking_bicycle.svg
Works reasonable well on 16x16, but could perhaps be crisper.

**Comment by nebulon42** [comment]
Bicycle parking is now available: ![parking-bicycle-16](https://cloud.githubusercontent.com/assets/3531092/5993008/8fff6156-aa41-11e4-99a1-e2d50b1050ff.png)

**Comment by mkoniecz** [comment]
Thanks!
