### ISSUE TITLE
Add icon for amenity=hunting_stand

### ISSUE THREAD

**Issue by math1985** [nebulon42/osmic#7]
Would it be possible to add an icon for amenity=hunting_stand?

Example, but needs much thicker lines: http://osm-icons.org/images/8/8f/12076.svg

**Comment by nebulon42** [comment]
Didn't know that this is such a widespread feature.

**Comment by nebulon42** [comment]
There is now an icon for hunting stand: [hunting-stand-16.svg](https://github.com/nebulon42/osmic/blob/master/outdoor/hunting-stand-16.svg)
Preview: ![hunting-stand-16](https://cloud.githubusercontent.com/assets/3531092/5891902/c0f08cf8-a4ac-11e4-819f-cb193fddf9bd.png)

Please let me know if you have any comments to it.

**Comment by math1985** [comment]
Looks fine to me.

Alternatively, maybe remove the white lines and add a window?

**Comment by nebulon42** [comment]
Easy change: ![hunting-stand-162](https://cloud.githubusercontent.com/assets/3531092/5891931/0cb90cb8-a4ae-11e4-8832-50aa25934c29.png)
I think its harder to identify though.

**Comment by mkoniecz** [comment]
Maybe it would better with longer legs?

Looks better with white line.

**Comment by nebulon42** [comment]
Yes, maybe: ![hunting-stand-16](https://cloud.githubusercontent.com/assets/3531092/5892161/d735ca7e-a4b5-11e4-95bd-306d5c542067.png)

**Comment by math1985** [comment]
Last one looks best to me.

**Comment by nebulon42** [comment]
Yes, I agree.

**Comment by mkoniecz** [comment]
I would consider even taller legs.

**Comment by nebulon42** [comment]
Difficult, because the "hut" itself starts to vanish: ![hunting-stand-16](https://cloud.githubusercontent.com/assets/3531092/5892912/57016284-a4d1-11e4-9f59-deb779059eab.png)
I think the current version is the best compromise.
