### ISSUE TITLE
Add icon for amenity=nightclub

### ISSUE THREAD

**Issue by math1985** [nebulon42/osmic#8]
Would it be possible to add an icon for amenity=nightclub?

Osm-icons has http://osm-icons.org/wiki/File:12092.svg, but this does not work on low resolution.

**Comment by nebulon42** [comment]
I thought about this one already, but found it hard to come up with a clear representation. I will think some more.

**Comment by nebulon42** [comment]
Icon of Potlatch: https://github.com/openstreetmap/potlatch2/blob/master/resources/icons/food_nightclub.n.16.png

**Comment by nebulon42** [comment]
I have two proposals.
Disco ball: ![nightclub-16](https://cloud.githubusercontent.com/assets/3531092/6318630/67857ede-ba9c-11e4-9be3-3b9890e1708b.png)
Musical note: ![nightclub-164](https://cloud.githubusercontent.com/assets/3531092/6318632/71763604-ba9c-11e4-8cb5-d7b101fcdfbd.png)

What do you think?
Cross-ref: https://github.com/gravitystorm/openstreetmap-carto/issues/456
cc @mkoniecz @daganzdaanda

**Comment by daganzdaanda** [comment]
The proposals both look good.
The notes might come in handy if we ever want an icon for a concert hall or similar. I guess for that reason I'd take the disco ball for "nightclub". But I would be perfectly happy with the notes, too.
BTW: the Potlatch combination isn't bad either, and might work too.

**Comment by nebulon42** [comment]
For completeness reasons I have quickly added the Potlatch version too. It is currently not tall enough as you can see compared to the text.

**Comment by nebulon42** [comment]
@math1985 @mkoniecz Please briefly tell me your preference, I can then create a PR.

**Comment by mkoniecz** [comment]
In this particular case I have no strong opinion
- the first one has the best chance to be an unique symbol
- seems easy to confuse with other things, but it should be mitigated by context
- the third one seems to be the easiest one to guess

**Comment by math1985** [comment]
Alternatives: would something like [this](http://wiki.openstreetmap.org/w/images/b/b1/Nightclub.png) or [this](http://upload.wikimedia.org/wikipedia/commons/c/c3/Party_icon.svg) work on 16px?

I also remember having seen a dancing woman sometime in one of the OSM projects. Does anyone know where I might have seen that?

**Comment by HolgerJeromin** [comment]
math: i think this was josm.

**Comment by nebulon42** [comment]
Thanks.
@math1985 Since you are asking for alternatives I assume you are not too happy with the two (three) provided? :)

I have already tried the vinyl, it did not work well. Also the dancers are very hard to draw + it might be easily confused with running or smth.

**Comment by math1985** [comment]
I think the discoball is hard to recognize, even for someone who knows it's a nightclub.

The music note works reasonably well. It might perhaps be confused with live music.

Last option is also fine with me, although I'd prefer the icons to be as simple as possible.

**Comment by nebulon42** [comment]
I'm also not convinced about any of the alternatives, but I will now for a start take the musical note.
